from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parent.parent
DATA=json.loads((ROOT/'tools/v2-content.json').read_text())
def e(s): return html.escape(str(s),quote=True)
def label(s): return '<span class="eyebrow" data-scramble>[ '+e(s.split(' — ')[-1])+' ]</span>'
def button(text,href='#contact',extra=''): return f'<a class="button" href="{href}" {extra}><span>{e(text)}</span><span aria-hidden="true">↗</span></a>'
old=(ROOT/'dist/ru/index.html').read_text()
logo=re.search(r'<svg class="brand-pixels".*?</svg>',old).group()
icons=re.findall(r'<svg class="contact-pixel-icon".*?</svg>',old)
for lang,d in DATA.items():
 ru=lang=='ru';pre='../' if ru else './';path=ROOT/('dist/v2/ru' if ru else 'dist/v2');path.mkdir(parents=True,exist_ok=True)
 h=d['hero'];a=d['about'];s=d['services'];t=d['team'];p=d['process'];pr=d['product'];ct=d['contact'];f=d['faq'];ch=d['challenges'];rv=d['reviews']
 tr=lambda r,n:r if ru else n
 nav=''.join(f'<a href="{n["href"]}">{e(n["text"])}</a>' for n in d['navigation'])
 catrows=''
 tags=[['DESIGN','DEVELOPMENT'],['SEARCH','AI'],['PAID MEDIA','PERFORMANCE'],['CONTENT','COMMUNITY'],['MOBILE','CUSTOM'],['SYSTEMS','DATA']]
 for i,c in enumerate(s['categories']):
  items=''.join(f'<a href="#contact" data-service="{e(o["service_choice"])}">{e(o["text"])} <span aria-hidden="true">↗</span></a>' for o in c['offerings'])
  catrows+=f'''<details class="service-row" id="service-{i+1}"><summary><span class="service-name"><sup class="mono">0{i+1}</sup>{e(c['title'])}</span><span class="service-tags mono"><span>{tags[i][0]}</span><span>{tags[i][1]}</span></span><span class="service-toggle mono">( <span class="view-word">{tr('СМОТРЕТЬ','EXPLORE')}</span> <b>+</b> )</span><span class="service-preview"><img src="{pre}assets/service-{i+1}.svg" alt="" loading="lazy"><span class="preview-type" aria-hidden="true">{['WEB.','GEO.','ADS.','SOCIAL.','APP.','SYNC.'][i]}</span></span></summary><div class="service-content"><p>{e(c['description'])}</p><div class="service-offerings">{items}</div><img src="{pre}assets/service-{i+1}.svg" alt="" loading="lazy"></div></details>'''
 stats=''.join(f'<article><span class="stat-value">{e(x["value"])}</span><h3>{e(x["title"])}</h3><p>{e(x["description"])}</p></article>' for x in a['stats'])
 steps=''.join(f'<article class="process-step" data-reveal><span class="mono">[ {e(x["number"])} ]</span><h3>{e(x["title"])}</h3><p>{e(x["description"])}</p><span class="step-mark" aria-hidden="true">↗</span></article>' for x in p['steps'])
 challenges=''.join(f'<details class="question"><summary><span class="mono">{e(x["number"])}</span><h3>{e(x["title"])}</h3><b>+</b></summary><p>{e(x["description"])}</p></details>' for x in ch['items'])
 faq=''.join(f'<details class="question"><summary><span class="mono">0{i+1}</span><h3>{e(x["question"])}</h3><b>+</b></summary><p>{e(x["answer"])}</p></details>' for i,x in enumerate(f['items']))
 team=''.join(f'<article class="team-item" data-reveal><div class="team-art art-{i}" aria-hidden="true"><span>{["Aa","</>","↗"][i]}</span><div class="art-grid"></div><small class="mono">S–AIM / 0{i+1}</small></div><span class="eyebrow">[ {e(x["subtitle"])} ]</span><h3>{e(x["title"])}</h3><p>{e(x["description"])}</p></article>' for i,x in enumerate(t['items']))
 reviews=''.join(f'<article class="review"><div class="review-face" aria-hidden="true">{["◕","◡","◒","◠"][i]}<span>·</span>{["◕","◡","◒","◠"][i]}</div><span class="eyebrow">{e(x["example_label"])}</span><span class="review-category">{e(x["category"])}</span><h3>{e(x["title"])}</h3><p>{e(x["description"])}</p><details><summary>{e(x["read_more"])} <b>+</b></summary><p>{e(x["full_text"])}</p></details><footer>{e(x["author"])}<span>{e(x["author_role"])}</span></footer></article>' for i,x in enumerate(rv['items']))
 fields=''
 for x in ct['fields']:
  attrs=f'name="{e(x["name"])}" id="field-{e(x["name"])}"'+(' required' if x['required'] else '')
  if x['tag']=='select': control=f'<select {attrs}>'+''.join(f'<option>{e(z)}</option>' for z in x['options'])+'</select>'
  elif x['tag']=='textarea':control=f'<textarea {attrs} rows="3" placeholder="{e(x["placeholder"])}"></textarea>'
  else:control=f'<input {attrs} type="{e(x["type"])}" placeholder="{e(x["placeholder"])}" autocomplete="{ {"name":"name","email":"email","company":"organization"}[x["name"]]}">'
  fields+=f'<div class="field field-{x["name"]}"><label for="field-{x["name"]}">{e(x["label"])}</label>{control}</div>'
 first=h['title'].split('. ')[0]+'.';rest=h['title'][len(first):].strip()
 languages=f'<a href="{pre}ru/" lang="ru" hreflang="ru"'+(' aria-current="page"' if ru else '')+'>RU</a><span>/</span>'+f'<a href="{pre}" lang="en" hreflang="en"'+(' aria-current="page"' if not ru else '')+'>EN</a>'
 contact_social=''.join(f'<a href="#contact" title="{e(ct["demo_note"])}">{icons[i]}{name}</a>' for i,name in enumerate(['Telegram','WhatsApp']))
 doc=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1b1e1b"><title>{e(d['title'])}</title><meta name="description" content="{e(d['meta_description'])}"><link rel="icon" href="{pre}../favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="{pre}style.css"><script src="{pre}script.js" defer></script><script src="{pre}hero-motion.js" defer></script></head>
<body><a class="skip-link" href="#main">{e(d['skip_link'])}</a><div id="top"></div>
<header class="floating-header"><a class="brand" href="#top" aria-label="S–AIM">{logo}</a><nav aria-label="{tr('Основная навигация','Main navigation')}">{nav}</nav><button class="menu-button" aria-expanded="false" aria-controls="mobile-menu" aria-label="{tr('Открыть меню','Open menu')}"><span></span><span></span></button></header>
<aside class="studio-dock"><a class="contact-dock" href="#contact"><span class="pixel-plus" aria-hidden="true">✳</span><span class="mono">{tr('НА СВЯЗИ','GET IN TOUCH')}</span><span>↗</span></a><details class="studio-widget" open><summary class="mono">{tr('ЭТО S–AIM','THIS IS S–AIM')} <span>( <b>+</b> )</span></summary><a href="#about" class="widget-art" aria-label="{tr('О студии','About the studio')}"><span>S–<br>AIM</span><small class="mono">DESIGN / CODE / GROW</small></a></details></aside>
<div class="mobile-menu" id="mobile-menu" hidden><nav>{nav}<a href="#product">{tr('Складские системы','Inventory systems')}</a><a href="#contact">{e(h['cta'])}</a></nav><div class="language-switch mono">{languages}</div></div>
<main id="main"><section class="hero" aria-labelledby="hero-title"><canvas data-hero-canvas aria-hidden="true"></canvas><div class="hero-shade"></div><div class="hero-coordinate mono" aria-hidden="true">DIGITAL MATTER<br>001 — S/A</div><div class="hero-body"><div><span class="eyebrow hero-kicker" data-scramble>[ {tr('МЫ — S–AIM','WE ARE S–AIM')} ]</span><h1 id="hero-title">{e(first)}</h1></div><p>{e(rest)}</p></div><div class="hero-footer mono"><span>{tr('НЕЗАВИСИМАЯ DIGITAL-СТУДИЯ','INDEPENDENT DIGITAL STUDIO')}</span><span>{tr('ДЛЯ МАЛОГО И СРЕДНЕГО БИЗНЕСА','FOR SMALL & MEDIUM BUSINESSES')}</span><a class="scroll-link" href="#services">{tr('ЛИСТАЙТЕ ВНИЗ','SCROLL TO EXPLORE')} <span>↓</span></a><div class="language-switch">{languages}</div></div></section>
<section class="section services-section" id="services"><div class="intro-grid" data-reveal><h2 class="editorial-heading">{e(s['title'])}</h2><div>{label(s['label'])}<p>{e(s['description'])}</p></div></div><div class="service-list">{catrows}</div><div class="services-bottom"><p>{e(h['description'])}</p>{button(h['cta'])}</div></section>
<section class="section about-section" id="about"><div class="dot-field" aria-hidden="true"></div>{label(a['label'])}<h2 class="display-heading" data-reveal>{e(a['title_lines'][0])}<br><span>{e(a['title_lines'][1])}</span></h2><div class="about-copy" data-reveal>{''.join('<p>'+e(x)+'</p>' for x in a['paragraphs'])}</div><div class="stats">{stats}</div><p class="connecting-note">{e(h["marquee"].replace(" ／", ".").rstrip(" ."))}.</p></section>
<section class="section challenges-section" id="challenges"><div class="split-heading">{label(ch['label'])}<h2 data-reveal>{e(ch['title'])}</h2><p>{e(ch['description'])}</p></div><div class="questions">{challenges}</div></section>
<section class="section process-section" id="process"><div class="intro-grid"><h2 class="editorial-heading" data-reveal>{e(p['title'])}</h2><div>{label(p['label'])}<p>{e(p['description'])}</p></div></div><div class="process-steps">{steps}</div><details class="principles"><summary>{e(p['principles_title'])}<span>+</span></summary><ul>{''.join('<li>'+e(x)+'</li>' for x in p['principles'])}</ul></details></section>
<section class="product-section" id="product"><div class="product-visual"><img src="{pre}assets/service-6.svg" alt="" loading="lazy"><span class="mono">S–AIM / SYSTEMS</span></div><div class="product-copy">{label(pr['label'])}<h2 data-reveal>{e(pr['title'])}</h2><p>{e(pr['description'])}</p><dl>{''.join('<div><dt>'+e(x['label'])+'</dt><dd>'+e(x['description'])+'</dd></div>' for x in pr['features'])}</dl>{button(pr['cta'],extra='data-service="'+e(ct['fields'][3]['options'][-1])+'"')}</div></section>
<section class="section team-section" id="team"><div class="intro-grid"><h2 class="editorial-heading" data-reveal>{e(t['title'])}</h2><div>{label(t['label'])}<p>{e(t['description'])}</p></div></div><div class="team-grid">{team}</div><div class="capabilities"><h3>{e(d['capabilities']['title'])}</h3><p>{e(d['capabilities']['description'])}</p></div></section>
<div class="marquees" aria-label="{e(d['capabilities']['title'])}">{''.join('<div class="marquee"><div class="marquee-track"><span>'+e(x)+' </span><span aria-hidden="true">'+e(x)+' </span></div></div>' for x in d['capabilities']['marquees'])}</div>
<section class="section reviews-section" id="reviews"><div class="reviews-heading">{label(rv['label'])}<h2>{e(rv['title'])}</h2><p>{e(rv['disclaimer'])}</p></div><div class="reviews-grid">{reviews}</div></section>
<section class="section faq-section" id="faq"><div class="split-heading">{label(f['label'])}<h2 data-reveal>{e(f['title'])}</h2><p>{e(f['description'])}</p></div><div class="questions">{faq}</div></section>
<section class="section contact-section" id="contact"><div class="contact-top">{label(ct['label'])}<h2 class="display-heading" data-reveal>{e(ct['title'])}</h2></div><div class="contact-grid"><div class="contact-info"><p>{e(ct['description'])}</p><a class="contact-email" href="{ct['email_href']}">{e(ct['email'])} ↗</a><a class="contact-phone" href="tel:+70000000000">{e(ct['phone'])}</a><div class="contact-social">{contact_social}</div><small>{e(ct['demo_note'])}</small><div class="contact-sigil" aria-hidden="true">↗</div></div><form id="contact-form">{fields}<div class="form-bottom"><p>{e(ct['form_note'])}</p><button class="button" type="submit"><span>{e(ct['submit'])}</span><span>↗</span></button></div><div id="form-preview" hidden aria-live="polite"><h3>{e(ct['preview_title'])}</h3><p>{e(ct['preview_note'])}</p><pre></pre><button type="button" class="button" id="download-brief">{e(ct['download'])}</button></div></form></div></section>
</main><footer class="footer"><a class="footer-wordmark" href="#top" aria-label="{tr('Наверх','Back to top')}">S–AIM<span>↗</span></a><div class="footer-meta mono"><span>© 2026 S–AIM</span><span>DESIGN / DEVELOPMENT / GROWTH</span><button class="motion-button" aria-pressed="false">{tr('ОСТАНОВИТЬ АНИМАЦИЮ','PAUSE MOTION')} Ⅱ</button><div class="language-switch">{languages}</div></div></footer><div class="cursor-label mono" aria-hidden="true">{tr('СМОТРЕТЬ','EXPLORE')} ↗</div></body></html>'''
 (path/'index.html').write_text(doc)
print('Built v2 EN and RU pages')
